[package]
name = "tailcall-enterprise"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
postgrest = "1.6.0"
keygen-rs = "0.3.1"