openapi: 3.0.0
x-optic-url: "https://app.useoptic.com/organizations/febf8ac6-ee67-4565-b45a-5c85a469dca7/apis/_0fKWqUvhs9ssYNkq1k-c"
"x-optic-standard": "@febf8ac6-ee67-4565-b45a-5c85a469dca7/Fz6KU3_wMIO5iJ6_VUZ30"
info:
  version: 2.2.0
  title: APIs.guru
  description: >
    Wikipedia for Web APIs. Repository of API definitions in OpenAPI format.

    **Warning**: If you want to be notified about changes in advance please join our [Slack channel](https://join.slack.com/t/mermade/shared_invite/zt-g78g7xir-MLE_CTCcXCdfJfG3CJe9qA).

    Client sample: [[Demo]](https://apis.guru/simple-ui) [[Repo]](https://github.com/APIs-guru/simple-ui)
  contact:
    name: APIs.guru
    url: https://APIs.guru
    email: mike.ralphson@gmail.com
  license:
    name: CC0 1.0
    url: https://github.com/APIs-guru/openapi-directory#licenses
  x-logo:
    url: https://apis.guru/branding/logo_vertical.svg
externalDocs:
  url: https://github.com/APIs-guru/openapi-directory/blob/master/API.md
servers:
  - url: https://api.apis.guru/v2
security: []
tags:
  - name: APIs
    description: Actions relating to APIs in the collection
components:
  schemas:
    ApiVersion:
      properties:
        added:
          description: Timestamp when the version was added
          type: string
          format: date-time
        updated:
          description: Timestamp when the version was updated
          type: string
          format: date-time
        swaggerUrl:
          description: URL to OpenAPI definition in JSON format
          type: string
          format: url
        swaggerYamlUrl:
          description: URL to OpenAPI definition in YAML format
          type: string
          format: url
        link:
          description: Link to the individual API entry for this API
          type: string
          format: url
        info:
          description: Copy of `info` section from OpenAPI definition
          type: object
          minProperties: 1
        externalDocs:
          description: Copy of `externalDocs` section from OpenAPI definition
          type: object
          minProperties: 1
        openapiVer:
          description: The value of the `openapi` or `swagger` property of the source definition
          type: string
      additionalProperties: false