name: 'Deploy to tailcall edge'
description: 'This action deploys files to tailcall edge'

inputs:
  file-path:
    description: 'Relative path of the file to deploy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install Wrangler
      shell: bash
      run: npm install -g wrangler
    - name: Install tailcall
      shell: bash
      run: npm install -g @tailcallhq/tailcall
    - name: check config]
      shell: bash
      run: |
        tailcall check ${{ inputs.file-path }}
    - run: |
        echo 'account_id = "59eda2a637301830ad43a6e3e4419346"' > wrangler.toml
        wrangler r2 object put configs/${{ inputs.file-path }} --file=${{ inputs.file-path }}
      env:
        CF_API_TOKEN: SvpRCgm6el9LSyQM4rOfQ9TdjqIQqgr47uSxeoaW
        CF_API_EMAIL: amit@taicall.run
      shell: bash
